In [2]:
import sys
module_path = "/root/dacon"
sys.path.append(module_path)
import torch
device = "cuda"
from models.unet.UNet3Plus import UNet3Plus_DeepSup_CGM
import yaml

with open("/home/work/Dacon-YAI/devch/models/unet3plus_deepsup_cgm.yaml") as f:
    cfg = yaml.safe_load(f)

model = UNet3Plus_DeepSup_CGM(**cfg["model"])
filename = "/home/work/Dacon-YAI/devch/models/ckpt/unet3plus_deepsup_cgm/Unet3plus_deepsup_cgm_shallow_266_07-21-14:22"
model.load_state_dict(torch.load(filename))
model.to(device).eval()

FileNotFoundError: [Errno 2] No such file or directory: '/home/work/Dacon-YAI/devch/models/unet3plus_deepsup_cgm.yaml'

In [7]:
import albumentations as A
from albumentations.pytorch import ToTensorV2

transform = A.Compose(
    [   
        A.Normalize(),
        ToTensorV2()
    ])

In [11]:
import cv2
image = cv2.imread("/home/work/Dacon-YAI/data/test_img/TEST_00001.png")
# print(img_path.replace(".","data"))
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

image = transform(image=image)["image"].unsqueeze(0)

In [12]:
image

tensor([[[[-0.9363, -0.9363, -1.0733,  ..., -1.5185, -1.6042, -1.6727],
          [-1.5528, -1.5528, -1.4158,  ..., -1.4329, -1.2959, -1.3473],
          [-1.6555, -1.6898, -1.5528,  ..., -1.4500, -1.3473, -1.3644],
          ...,
          [-1.6213, -1.6042, -1.5870,  ...,  0.5536,  0.4851,  0.4508],
          [-1.6384, -1.6727, -1.6555,  ...,  0.4679,  0.4508,  0.5022],
          [-1.6384, -1.6384, -1.6042,  ...,  0.5536,  0.6563,  0.8961]],

         [[-0.4776, -0.4776, -0.6176,  ..., -1.0903, -1.1779, -1.2479],
          [-1.1078, -1.1253, -0.9678,  ..., -1.0028, -0.8627, -0.8978],
          [-1.2304, -1.2654, -1.1253,  ..., -1.0203, -0.9153, -0.9328],
          ...,
          [-1.1954, -1.1779, -1.1604,  ...,  0.4503,  0.3803,  0.3102],
          [-1.2304, -1.2654, -1.2479,  ...,  0.3978,  0.3978,  0.4503],
          [-1.2304, -1.2304, -1.1954,  ...,  0.4853,  0.5903,  0.8354]],

         [[-0.2881, -0.2532, -0.3578,  ..., -0.7587, -0.8284, -0.8981],
          [-0.8458, -0.8458, -

In [13]:
result = model(image)

In [14]:
result

(tensor([[[[0.5000, 0.5000, 0.5000,  ..., 0.5000, 0.5000, 0.5000],
           [0.5000, 0.5000, 0.5000,  ..., 0.5000, 0.5000, 0.5000],
           [0.5000, 0.5000, 0.5000,  ..., 0.5000, 0.5000, 0.5000],
           ...,
           [0.5000, 0.5000, 0.5000,  ..., 0.5000, 0.5000, 0.5000],
           [0.5000, 0.5000, 0.5000,  ..., 0.5000, 0.5000, 0.5000],
           [0.5000, 0.5000, 0.5000,  ..., 0.5000, 0.5000, 0.5000]]]],
        grad_fn=<SigmoidBackward0>),
 tensor([[[[0.5000, 0.5000, 0.5000,  ..., 0.5000, 0.5000, 0.5000],
           [0.5000, 0.5000, 0.5000,  ..., 0.5000, 0.5000, 0.5000],
           [0.5000, 0.5000, 0.5000,  ..., 0.5000, 0.5000, 0.5000],
           ...,
           [0.5000, 0.5000, 0.5000,  ..., 0.5000, 0.5000, 0.5000],
           [0.5000, 0.5000, 0.5000,  ..., 0.5000, 0.5000, 0.5000],
           [0.5000, 0.5000, 0.5000,  ..., 0.5000, 0.5000, 0.5000]]]],
        grad_fn=<SigmoidBackward0>),
 tensor([[[[0.5000, 0.5000, 0.5000,  ..., 0.5000, 0.5000, 0.5000],
           [0.500