In [8]:
import torch

def dotProduct(seg, cls):
    B, N, H, W = seg.size()
    seg = seg.view(B, N, H * W)
    final = torch.einsum("ijk,ij->ijk", [seg, cls])
    final = final.view(B, N, H, W)
    return final

In [16]:
seg = torch.rand(2,1,4,4)
seg

tensor([[[[0.4055, 0.7454, 0.3303, 0.1736],
          [0.2081, 0.2903, 0.6503, 0.5204],
          [0.0198, 0.4589, 0.8852, 0.5979],
          [0.4754, 0.2286, 0.6220, 0.9284]]],


        [[[0.6634, 0.2717, 0.2487, 0.9322],
          [0.6603, 0.9969, 0.0418, 0.6284],
          [0.8117, 0.1622, 0.0442, 0.1281],
          [0.6391, 0.7414, 0.9232, 0.4868]]]])

In [17]:
cls = torch.tensor([[1],[0]])
cls

tensor([[1],
        [0]])

In [18]:
dotProduct(seg,cls)

tensor([[[[0.4055, 0.7454, 0.3303, 0.1736],
          [0.2081, 0.2903, 0.6503, 0.5204],
          [0.0198, 0.4589, 0.8852, 0.5979],
          [0.4754, 0.2286, 0.6220, 0.9284]]],


        [[[0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000]]]])

: 